-- Analyze the table as required
ANALYZE TABLE BOOKS;

-- Print full description of the BOOKS table
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'BOOKS';
use ALX_BOOK_STORE;